#define M_NEWLINE "\n"

#define O_PLUS "+"
#define O_MINUS "-"
#define O_MULTI "*"
#define O_DIVIDE "/"

#define B_PIPE "|"
#define B_UPPER ">"
#define B_LOWER "<"
#define B_NOT "!"
#define B_LEAST ">="
#define B_MOST "<="
#define B_SIMILAR "~"

#define S_IFBEGIN "if"
#define S_ELSE "else"
#define S_ELIF "elif"
#define S_RETURN "return"
#define S_FUNC "function"
#define S_DEFINE "@rename"